/** Liste large de races de chiens (français), pour le sélecteur avec recherche. */
export const DOG_BREEDS: string[] = [
  "Croisé / Bâtard",
  "Affenpinscher",
  "Airedale Terrier",
  "Akita Américain",
  "Akita Inu",
  "Malamute de l'Alaska",
  "Berger de Beauce (Beauceron)",
  "Berger de Brie (Briard)",
  "Berger Allemand",
  "Berger Australien",
  "Berger Belge Groenendael",
  "Berger Belge Laekenois",
  "Berger Belge Malinois",
  "Berger Belge Tervueren",
  "Berger Blanc Suisse",
  "Berger des Pyrénées",
  "Berger des Shetland",
  "Berger Hollandais",
  "Berger Islandais",
  "Berger Picard",
  "Bearded Collie",
  "Bichon Bolonais",
  "Bichon Frisé",
  "Bichon Havanais",
  "Bichon Maltais",
  "Barbet",
  "Basenji",
  "Basset Artésien Normand",
  "Basset Bleu de Gascogne",
  "Basset Fauve de Bretagne",
  "Basset Hound",
  "Beagle",
  "Beagle-Harrier",
  "Bedlington Terrier",
  "Bichon Coton de Tuléar",
  "Bobtail (Old English Sheepdog)",
  "Border Collie",
  "Border Terrier",
  "Bouledogue Américain",
  "Bouledogue Français",
  "Bouvier Australien (Cattle Dog)",
  "Bouvier Bernois",
  "Bouvier des Flandres",
  "Boxer",
  "Boston Terrier",
  "Braque Allemand",
  "Braque de Weimar (Weimaraner)",
  "Braque du Bourbonnais",
  "Braque Français",
  "Braque Hongrois (Vizsla)",
  "Braque Italien (Bracco)",
  "Braque Saint-Germain",
  "Buhund Norvégien",
  "Bull Terrier",
  "Bull Terrier Miniature",
  "Bulldog Anglais",
  "Bulldog Continental",
  "Bullmastiff",
  "Cairn Terrier",
  "Caniche Grand",
  "Caniche Moyen",
  "Caniche Nain",
  "Caniche Toy",
  "Cane Corso",
  "Carlin (Pug)",
  "Cavalier King Charles Spaniel",
  "Chien Chinois à Crête",
  "Chien Courant Suisse",
  "Chien d'Eau Espagnol",
  "Chien d'Eau Portugais",
  "Chien de Berger Roumain",
  "Chien de Canaan",
  "Chien de Montagne des Pyrénées (Patou)",
  "Chien de Saint-Hubert",
  "Chien Finnois de Laponie",
  "Chien Loup de Saarloos",
  "Chien Loup Tchécoslovaque",
  "Chien Nu du Mexique (Xoloitzcuintle)",
  "Chihuahua",
  "Chow Chow",
  "Cocker Américain",
  "Cocker Anglais",
  "Colley à Poil Court",
  "Colley à Poil Long",
  "Cursinu (Chien Corse)",
  "Dalmatien",
  "Dogue Allemand",
  "Dogue Argentin",
  "Dogue de Bordeaux",
  "Dobermann",
  "Épagneul Breton",
  "Épagneul du Tibet",
  "Épagneul Japonais (Chin)",
  "Épagneul Nain Continental (Papillon)",
  "Épagneul Picard",
  "Épagneul Springer Anglais",
  "Eurasier",
  "Fox Terrier à Poil Dur",
  "Fox Terrier à Poil Lisse",
  "Foxhound Anglais",
  "Galgo Espagnol",
  "Golden Retriever",
  "Grand Bouvier Suisse",
  "Greyhound (Lévrier Anglais)",
  "Griffon Belge",
  "Griffon Bruxellois",
  "Griffon Korthals",
  "Griffon Nivernais",
  "Hovawart",
  "Husky Sibérien",
  "Jack Russell Terrier",
  "Kangal (Berger d'Anatolie)",
  "Keeshond",
  "Kelpie Australien",
  "King Charles Spaniel",
  "Komondor",
  "Kuvasz",
  "Labrador Retriever",
  "Labradoodle",
  "Lagotto Romagnolo",
  "Landseer",
  "Léonberg",
  "Lévrier Afghan",
  "Lévrier Barzoï (Borzoï)",
  "Lévrier Irlandais (Wolfhound)",
  "Lévrier Whippet",
  "Lhassa Apso",
  "Malinois",
  "Mastiff",
  "Mâtin de Naples",
  "Mâtin Espagnol",
  "Montagne des Pyrénées",
  "Mudi",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever",
  "Otterhound",
  "Parson Russell Terrier",
  "Pékinois",
  "Petit Basset Griffon Vendéen",
  "Petit Brabançon",
  "Petit Chien Lion (Löwchen)",
  "Pinscher Nain",
  "Pinscher Moyen",
  "Podenco Ibicenco",
  "Pointer Anglais",
  "Pomsky",
  "Poodle (Caniche)",
  "Épagneul Cavalier",
  "Rottweiler",
  "Saint-Bernard",
  "Saluki",
  "Samoyède",
  "Schipperke",
  "Schnauzer Géant",
  "Schnauzer Moyen",
  "Schnauzer Nain",
  "Setter Anglais",
  "Setter Gordon",
  "Setter Irlandais Rouge",
  "Shar Peï",
  "Shiba Inu",
  "Shih Tzu",
  "Spitz Allemand",
  "Spitz Finlandais",
  "Spitz Japonais",
  "Spitz Loup (Keeshond)",
  "Spitz Nain (Poméranien)",
  "Springer Spaniel",
  "Staffordshire Bull Terrier",
  "American Staffordshire Terrier (Amstaff)",
  "Teckel à Poil Dur",
  "Teckel à Poil Long",
  "Teckel à Poil Ras",
  "Terre-Neuve",
  "Terrier Australien",
  "Terrier Brésilien",
  "Terrier de Boston",
  "Terrier du Tibet",
  "Terrier Écossais (Scottish)",
  "Terrier Irlandais",
  "Terrier Irlandais à Poil Doux (Wheaten)",
  "Terrier Kerry Blue",
  "Terrier Tibétain",
  "Tosa Inu",
  "Volpino Italien",
  "Welsh Corgi Cardigan",
  "Welsh Corgi Pembroke",
  "Welsh Terrier",
  "West Highland White Terrier (Westie)",
  "Yorkshire Terrier",
  "Autre",
];

/** Recherche insensible aux accents/casse. */
export function normalizeBreed(s: string): string {
  return s
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .trim();
}
