/**
 * Tours qu'un chien peut apprendre, classés du plus connu / facile
 * au moins connu / difficile. Utilisé par le sélecteur avec recherche.
 */
export const DOG_TRICKS: string[] = [
  // Bases
  "Assis",
  "Couché",
  "Debout",
  "Pas bouger",
  "Viens (rappel)",
  "Au pied",
  "Donne la patte",
  "L'autre patte",
  "Stop",
  "Non / Laisse",
  "Doucement (prendre délicatement)",
  "Va au panier",
  "Monte / Descends",
  "Attends (avant de manger)",
  // Intermédiaire
  "Le check (tape m'en cinq)",
  "Fais le beau (assis mendiant)",
  "Roule (fais le rouleau)",
  "Fais le mort",
  "Tourne sur toi-même",
  "Recule",
  "Saute (par-dessus un obstacle)",
  "Rapporte",
  "Lâche / Donne",
  "Cherche (un objet)",
  "Aboie sur demande (parle)",
  "Silence (arrête d'aboyer)",
  "Bisou",
  "Fais un câlin",
  "Slalom entre les jambes",
  "Fais coucou (salue de la patte)",
  "Touch (touche la main du museau)",
  // Avancé
  "Range tes jouets",
  "Apporte un objet nommé",
  "Fais le tour (contourne un objet)",
  "Marche au pied sans laisse",
  "Fais la révérence",
  "Croise les pattes",
  "Ferme la porte / le tiroir",
  "Éteins la lumière",
  "Tiens un objet en équilibre",
  "Fais le serpent (rampe)",
  "Marche sur les pattes arrière",
  "Fais semblant d'avoir honte (cache le museau)",
  "Compte / réponds (aboiements)",
  "Distingue les couleurs / objets",
  "Cherche et rapporte les clés",
];
